version: '3.7'

services:
  web:
    env_file:
      - .env 
    build: 
      context: .
 
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx


  nginx:
    build: ./nginx
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  
  postgres_data:

